std = "lua51" -- WoW runs Lua 5.1
max_line_length = false
unused_args = false -- event handler and callback signatures are fixed by the API

exclude_files = {
    "Libs/**",
}

-- WoW API, FrameXML and libraries
read_globals = {
    "C_Item",
    "C_MountJournal",
    "ConfirmLootRoll",
    "CopyTable",
    "C_PetJournal",
    "CreateFrame",
    "GetDetailedItemLevelInfo",
    "GetInstanceInfo",
    "GetInventoryItemLink",
    "GetItemClassInfo",
    "GetItemCount",
    "GetItemInfo",
    "GetItemInfoInstant",
    "GetItemSubClassInfo",
    "GetLootRollItemInfo",
    "GetLootRollItemLink",
    "INVSLOT_BACK",
    "INVSLOT_BODY",
    "INVSLOT_CHEST",
    "INVSLOT_FEET",
    "INVSLOT_FINGER1",
    "INVSLOT_FINGER2",
    "INVSLOT_HAND",
    "INVSLOT_HEAD",
    "INVSLOT_LEGS",
    "INVSLOT_MAINHAND",
    "INVSLOT_NECK",
    "INVSLOT_OFFHAND",
    "INVSLOT_SHOULDER",
    "INVSLOT_TABARD",
    "INVSLOT_TRINKET1",
    "INVSLOT_TRINKET2",
    "INVSLOT_WAIST",
    "INVSLOT_WRIST",
    "IsEquippedItem",
    "IsInGroup",
    "IsPlayerSpell",
    "Item",
    "ITEM_LEVEL",
    "ItemLocation",
    "ITEM_QUALITY_COLORS",
    "ITEM_SPELL_KNOWN",
    "LE_PARTY_CATEGORY_INSTANCE",
    "LibStub",
    "RollOnLoot",
    "StaticPopup_Hide",
    "UnitClass",
    "WorldFrame",
}
